In [3]:
#MATH 3423 Final Test

In [4]:
#Student Name: Huy Huynh

In [6]:
from scipy import optimize

In [5]:
#Problem 2:

In [7]:
def F_2(x):
    return (3 - x[0])**2 + 150*((x[1] - x[0]**2))**2

In [8]:
# I use Powell Method for minimizing this function

In [9]:
optimize.minimize(F_2, [-1,1], method='Powell')

   direc: array([[8.92924215e-03, 5.44123217e-02],
       [9.83352979e-07, 5.83284984e-06]])
     fun: 2.6271040296122746e-27
 message: 'Optimization terminated successfully.'
    nfev: 1085
     nit: 37
  status: 0
 success: True
       x: array([3., 9.])

In [ ]:
# I use BFGS Method for minimizing this function

In [11]:
optimize.minimize(F_2, [-1,1], method =  'BFGS')

      fun: 2.201966360217826e-09
 hess_inv: array([[ 0.49455093,  2.96812896],
       [ 2.96812896, 17.81690262]])
      jac: array([ 5.96996554e-06, -9.88404558e-07])
  message: 'Optimization terminated successfully.'
     nfev: 288
      nit: 54
     njev: 72
   status: 0
  success: True
        x: array([2.99995308, 8.99971844])

In [12]:
#Problem 3

In [17]:
import numpy as np
from numpy.linalg import qr
import scipy.linalg as linalg
from numpy.linalg import eig

In [19]:
A = np.array([[1,-1,4],
            [1,4,-2],
            [1,4,2],
            [1,-1,0]])
A

array([[ 1, -1,  4],
       [ 1,  4, -2],
       [ 1,  4,  2],
       [ 1, -1,  0]])

In [20]:
# Problem A. Find the QR Factorization of A

In [21]:
Q, R = qr(A, 'complete')
print("Matrix Q (m x m)")
print(Q)
print(" ---------- ")
print("Matrix Q^T Q = I (m x m)")
print(Q.T.dot(Q))
print(" ---------- ")
print("Matrix R (m x n)")
print(R)
print(" ---------- ")

Matrix Q (m x m)
[[-0.5  0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5  0.5]
 [-0.5  0.5  0.5  0.5]]
 ---------- 
Matrix Q^T Q = I (m x m)
[[ 1.00000000e+00  2.77555756e-17  0.00000000e+00 -5.55111512e-17]
 [ 2.77555756e-17  1.00000000e+00  1.38777878e-16 -5.55111512e-17]
 [ 0.00000000e+00  1.38777878e-16  1.00000000e+00 -1.11022302e-16]
 [-5.55111512e-17 -5.55111512e-17 -1.11022302e-16  1.00000000e+00]]
 ---------- 
Matrix R (m x n)
[[-2. -3. -2.]
 [ 0. -5.  2.]
 [ 0.  0. -4.]
 [ 0.  0.  0.]]
 ---------- 


In [22]:
# Problem B. Find SVD of A

In [23]:
from numpy import array
from numpy.linalg import eig
from scipy.linalg import svd
from numpy import diag
from numpy import dot
from numpy import zeros
import scipy as sp

In [25]:
print("Original (m x n) A Matrix")
print(A)
print(" ------------- ")

# Perform Singular Value Decomposition
U, Sigma, V = np.linalg.svd(A, full_matrices= True)
Sigma =sp.linalg.diagsvd(Sigma,4,3)
#generate 
print("(m x m) U Matrix")
print(U)
print(" ------------- ")
print("(m x n) Singular Values in Vector Form")
print(Sigma)
print(" ------------- ")
print("(n x n) V^T Matrix")
print(V)

Original (m x n) A Matrix
[[ 1 -1  4]
 [ 1  4 -2]
 [ 1  4  2]
 [ 1 -1  0]]
 ------------- 
(m x m) U Matrix
[[-0.31327912  0.77156416  0.23779181 -0.5       ]
 [ 0.74808713 -0.14688895  0.41083973 -0.5       ]
 [ 0.56932221  0.61893411 -0.2068642   0.5       ]
 [-0.1345142   0.0057411   0.85549575  0.5       ]]
 ------------- 
(m x n) Singular Values in Vector Form
[[6.00328467 0.         0.        ]
 [0.         4.91120619 0.        ]
 [0.         0.         1.35669707]
 [0.         0.         0.        ]]
 ------------- 
(n x n) V^T Matrix
[[ 0.1448567   0.95238373 -0.26829418]
 [ 0.25438769  0.22619197  0.94027873]
 [ 0.95619216 -0.20445641 -0.20950928]]


In [26]:
#Problem C. Use the SVD to find A+

In [33]:
Ainv = np.dot(V.transpose(), np.dot(Sigma.transpose(), U.transpose()))
Ainv = np.round(Ainv)
print("The Pseudo-inverse of A is ")
print(Ainv)

The Pseudo-inverse of A is 
[[ 1.  1.  1.  1.]
 [-1.  4.  4. -1.]
 [ 4. -2.  2.  0.]]


In [35]:
#Problem D. Reconstruct A from its SVD factory

In [37]:
print("Reconstructed Original (m x n) A Matrix From SVD Factors")
AA = U.dot(Sigma.dot(V))
AA = np.round(AA)
print(AA)

Reconstructed Original (m x n) A Matrix From SVD Factors
[[ 1. -1.  4.]
 [ 1.  4. -2.]
 [ 1.  4.  2.]
 [ 1. -1.  0.]]


In [38]:
#Problem E. Why the rank of A cannot be 4?

In [40]:
#Answer: Because matrix A is 4x3, it has 3 NonZero Singular Values. As the result, the rank has to be 3 not 4

In [41]:
#Problem F. Find the Eigen values/ Vectors of ATA

In [59]:
from numpy import array
from numpy.linalg import eig
ATA = A.T @ A
print("Original (m x m) ATA Matrix")
print(ATA)
print(" ------------- ")
# factor
Eig_Values, Eig_Vectors = eig(ATA)
#
print("EigenValues of ATA")
print(Eig_Values)
print(" ------------- ")
#
print("EigenVectors of ATA")
print(Eig_Vectors)
print(" ------------- ")

Original (m x m) ATA Matrix
[[ 4  6  4]
 [ 6 34 -4]
 [ 4 -4 24]]
 ------------- 
EigenValues of ATA
[ 1.84062693 24.11994626 36.03942681]
 ------------- 
EigenVectors of ATA
[[-0.95619216  0.25438769 -0.1448567 ]
 [ 0.20445641  0.22619197 -0.95238373]
 [ 0.20950928  0.94027873  0.26829418]]
 ------------- 


In [44]:
#Problem 4

In [ ]:
#Problem A. Finf LU Factorization and solve Ax=b

In [46]:
A1=np.array([[ 3,-1,2],
            [-6,4,-5],
            [9,5,6]])
A1

array([[ 3, -1,  2],
       [-6,  4, -5],
       [ 9,  5,  6]])

In [48]:
b=np.array([[ 6],[-3],[2]])
b

array([[ 6],
       [-3],
       [ 2]])

In [53]:
# factorize
from scipy.linalg import lu
P, L, U = lu(A1)
print("Lower Triangular (n x n) L Matrix")
print(L)
print("Upper Triangular (n x n) U Matrix")
print(U)

Lower Triangular (n x n) L Matrix
[[ 1.          0.          0.        ]
 [-0.66666667  1.          0.        ]
 [ 0.33333333 -0.36363636  1.        ]]
Upper Triangular (n x n) U Matrix
[[ 9.          5.          6.        ]
 [ 0.          7.33333333 -1.        ]
 [ 0.          0.         -0.36363636]]


In [56]:
y = np.linalg.solve(L, b)
x = np.linalg.solve(U,y)
print("The solution x is:\n",x)

The solution x is:
 [[ 1.33333333e+00]
 [-9.08364293e-17]
 [-1.00000000e+00]]


In [58]:
# Problem B. Find the Eigenvalues of ATA

In [60]:
from numpy import array
from numpy.linalg import eig
A1TA1 = A1.T @ A1
print("Original (m x m) A1TA1 Matrix")
print(A1TA1)
print(" ------------- ")
# factor
Eig_Values, Eig_Vectors = eig(A1TA1)
#
print("EigenValues of A1TA1")
print(Eig_Values)
print(" ------------- ")
#
print("EigenVectors of A1TA1")
print(Eig_Vectors)
print(" ------------- ")

Original (m x m) A1TA1 Matrix
[[126  18  90]
 [ 18  42   8]
 [ 90   8  65]]
 ------------- 
EigenValues of A1TA1
[1.92993363e+02 7.47412194e-02 3.99318959e+01]
 ------------- 
EigenVectors of A1TA1
[[ 0.80766702  0.58794668  0.04463948]
 [ 0.12679212 -0.09924161 -0.98695231]
 [ 0.57584524 -0.80278877  0.15470118]]
 ------------- 


In [61]:
#Problem C. Find the Cholesky Factorization of A1TA1 and use it to solve A1TA1x=A1Tb

In [62]:
#Let's compute x by Cholesky factorization.

In [63]:
#𝐴𝑇𝐴𝑥=𝐴𝑇𝑏  <=>  𝐿𝐿𝑇𝑥=𝐴𝑇𝑏 
#let's find L first

In [64]:
L= np.linalg.cholesky(A1TA1)
print(L)

[[11.22497216  0.          0.        ]
 [ 1.60356745  6.27921742  0.        ]
 [ 8.01783726 -0.77352678  0.34050261]]


In [65]:
#𝐿𝐿𝑇𝑥=𝐴𝑇𝑏  <=> Ly=𝐴𝑇𝑏 with y =𝐿𝑇𝑥
#now I find y

In [66]:
y= np.linalg.solve(L,np.dot(A1.T,b))
print(y)

[[ 4.81070235]
 [-2.50258665]
 [-4.42653396]]


In [67]:
#now it is easy to solve x since y= LTx

In [68]:
x =np.linalg.solve(L.T,y)

In [69]:
print("The solution x is:\n",x)

The solution x is:
 [[ 10.]
 [ -2.]
 [-13.]]
