In [4]:
#MATH 3423 HW3
#Student Name: Huy Huynh

In [2]:
import numpy as np

In [3]:
A=np.array([[ 1, 6,-1, 4, 7],
          [-7, 0,12,-8, 2],
          [14, 4, 5, 3,35]])

print("==========\n matrix A:\n")
print(A)

b = np.array([[1],
              [2],
              [3]])

print("==========\n b:\n")
print(b)

 matrix A:

[[ 1  6 -1  4  7]
 [-7  0 12 -8  2]
 [14  4  5  3 35]]
 b:

[[1]
 [2]
 [3]]


In [4]:
#Q1. Use the QR-factorization to solve Ax=b

In [37]:
from numpy.linalg import qr
import scipy.linalg as linalg
from numpy.linalg import eig

Q, R = qr(A, 'complete')
print("Matrix Q (m x m)")
print(Q)
print(" ---------- ")
print("Matrix Q^T Q = I (m x m)")
print(Q.T.dot(Q))
print(" ---------- ")
print("Matrix R (m x n)")
print(R)
print(" ---------- ")

Matrix Q (m x m)
[[-0.06375767 -0.95305698 -0.29600227]
 [ 0.4463037  -0.29252244  0.84572078]
 [-0.8926074  -0.07818572  0.44400341]]
 ---------- 
Matrix Q^T Q = I (m x m)
[[ 1.00000000e+00  9.54042891e-17  4.75245870e-17]
 [ 9.54042891e-17  1.00000000e+00 -2.79202702e-17]
 [ 4.75245870e-17 -2.79202702e-17  1.00000000e+00]]
 ---------- 
Matrix R (m x n)
[[-15.68438714  -3.95297562   0.95636507  -6.50328247 -30.79495524]
 [  0.          -6.03108479  -2.94814091  -1.70660558  -9.99294402]
 [  0.           0.          12.66466861  -6.61776507  15.1595449 ]]
 ---------- 


In [38]:
R_1 = np.delete(R,[3,4],1)
R_1

array([[-15.68438714,  -3.95297562,   0.95636507],
       [  0.        ,  -6.03108479,  -2.94814091],
       [  0.        ,   0.        ,  12.66466861]])

In [39]:
x_1 = linalg.solve(R_1, Q.T @ b)
print(x_1)

[[0.08347245]
 [0.18864775]
 [0.21535893]]


In [40]:
#this is the case that i cannot solve Rx=Q_tranposexb or ATx=b or 
#then i apply the least square approach to solve it.
#Rx=QTb

#RTRx=RTQTB

#RTR X = ATb

A_trans = A.transpose()

z = np.dot(A_trans, b) 

R_trans = R.transpose()

y = np.dot(R_trans,R)

x = linalg.solve(y, z)

print("x is")
print(x)

x is
[[ 0.06524547]
 [ 0.18644102]
 [ 0.18728143]
 [-0.02279076]
 [ 0.01350755]]


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: LinAlgWarning: Ill-conditioned matrix (rcond=4.18316e-18): result may not be accurate.
  app.launch_new_instance()


In [11]:
#Compute the $||A-QR||_2$

In [12]:
linalg.norm(A-np.dot(Q,R))

1.4743828647775484e-14

In [13]:
#Q2 Find the pseudo-inverse of A and use it to solve: Ax=b

In [14]:
#In order to find pseudo-inverse of A or A+, I would start with SVD then find it.

In [21]:
from numpy import array
from numpy.linalg import eig
from scipy.linalg import svd
from numpy import diag
from numpy import dot
from numpy import zeros
import scipy as sp

In [29]:
print("Original (m x n) A Matrix")
print(A)
print(" ------------- ")

# Perform Singular Value Decomposition
U, Sigma, V = np.linalg.svd(A, full_matrices= True)
Sigma =sp.linalg.diagsvd(Sigma,3,5)
#generate 
print("(m x m) U Matrix")
print(U)
print(" ------------- ")
print("(m x n) Singular Values in Vector Form")
print(Sigma)
print(" ------------- ")
print("(n x n) V^T Matrix")
print(V)

Original (m x n) A Matrix
[[ 1  6 -1  4  7]
 [-7  0 12 -8  2]
 [14  4  5  3 35]]
 ------------- 
(m x m) U Matrix
[[-1.99151775e-01  1.63815921e-01 -9.66179546e-01]
 [-3.71281490e-04 -9.85941570e-01 -1.67090046e-01]
 [-9.79968588e-01 -3.29175547e-02  1.96412835e-01]]
 ------------- 
(m x n) Singular Values in Vector Form
[[39.11441663  0.          0.          0.          0.        ]
 [ 0.         16.35281964  0.          0.          0.        ]
 [ 0.          0.          6.1357723   0.          0.        ]]
 ------------- 
(n x n) V^T Matrix
[[-0.35577964 -0.1307647  -0.12029188 -0.09545183 -0.91254603]
 [ 0.40387904  0.05205373 -0.74358446  0.51636621 -0.12091408]
 [ 0.48131357 -0.81675553 -0.00926319 -0.31597641 -0.03634224]
 [-0.14922608 -0.39711588  0.44337706  0.78916169 -0.02590691]
 [-0.67555266 -0.39420856 -0.48573964 -0.04046751  0.38813349]]


In [24]:
#Now i use SVD to find pseudo-inverse

In [31]:
Ainv = np.dot(V.transpose(), np.dot(Sigma.transpose(), U.transpose()))
print(Ainv)

[[ 1.00000000e+00 -7.00000000e+00  1.40000000e+01]
 [ 6.00000000e+00  1.44328993e-15  4.00000000e+00]
 [-1.00000000e+00  1.20000000e+01  5.00000000e+00]
 [ 4.00000000e+00 -8.00000000e+00  3.00000000e+00]
 [ 7.00000000e+00  2.00000000e+00  3.50000000e+01]]


In [76]:
#I think because of Sigma value has been reduced by Python 
#then i have to use a inv in numpy to solve it.

In [32]:
Ainv = np.linalg.pinv(A)
print("The Pseudo-inverse of A is ")
print(Ainv)
np.dot(A,Ainv)

The Pseudo-inverse of A is 
[[-0.06993348 -0.03745442  0.02350805]
 [ 0.12979901  0.0191048  -0.02297386]
 [-0.00537782  0.04508547  0.00421406]
 [ 0.05541449 -0.02252706 -0.00876274]
 [ 0.00915767  0.00828847  0.02194287]]


array([[ 1.00000000e+00, -2.01227923e-16,  2.25514052e-16],
       [-4.85722573e-17,  1.00000000e+00,  7.63278329e-17],
       [-1.28369537e-16, -3.81639165e-16,  1.00000000e+00]])

In [33]:
#Use The Pseudo-inverse of A to solve Ax=b

In [34]:
x = Ainv @ b
print(x)

[[-0.07431816]
 [ 0.09908703]
 [ 0.09743531]
 [-0.01592783]
 [ 0.09156323]]


In [101]:
#Q3 Compute SVD of A and Ainv

In [102]:
#Let start with A

In [103]:
print("Original (m x n) A Matrix")
print(A)
print(" ------------- ")

# Perform Singular Value Decomposition
U, Sigma, V = np.linalg.svd(A, full_matrices=False)
Sigma =np.diag(Sigma)

print("(m x m) U Matrix")
print(U)
print(" ------------- ")
print("(m x n) Singular Values in Vector Form")
print(Sigma)
print(" ------------- ")
print("(n x n) V^T Matrix")
print(V)

Original (m x n) A Matrix
[[ 1  6 -1  4  7]
 [-7  0 12 -8  2]
 [14  4  5  3 35]]
 ------------- 
(m x m) U Matrix
[[-1.99151775e-01  1.63815921e-01 -9.66179546e-01]
 [-3.71281490e-04 -9.85941570e-01 -1.67090046e-01]
 [-9.79968588e-01 -3.29175547e-02  1.96412835e-01]]
 ------------- 
(m x n) Singular Values in Vector Form
[[39.11441663  0.          0.        ]
 [ 0.         16.35281964  0.        ]
 [ 0.          0.          6.1357723 ]]
 ------------- 
(n x n) V^T Matrix
[[-0.35577964 -0.1307647  -0.12029188 -0.09545183 -0.91254603]
 [ 0.40387904  0.05205373 -0.74358446  0.51636621 -0.12091408]
 [ 0.48131357 -0.81675553 -0.00926319 -0.31597641 -0.03634224]]


In [104]:
#Then with Ainv

In [112]:
Ainv = np.linalg.pinv(A)
print("The Pseudo-inverse of A is ")
print("Original (m x n) A Matrix")
print(Ainv)
print(" ------------- ")

# Perform Singular Value Decomposition
U, Sigma, V = np.linalg.svd(Ainv, full_matrices=False)
Sigma =np.diag(Sigma)

print("(m x m) U Matrix")
print(U)
print(" ------------- ")
print("(m x n) Singular Values in Vector Form")
print(Sigma)
print(" ------------- ")
print("(n x n) V^T Matrix")
print(V)

The Pseudo-inverse of A is 
Original (m x n) A Matrix
[[-0.06993348 -0.03745442  0.02350805]
 [ 0.12979901  0.0191048  -0.02297386]
 [-0.00537782  0.04508547  0.00421406]
 [ 0.05541449 -0.02252706 -0.00876274]
 [ 0.00915767  0.00828847  0.02194287]]
 ------------- 
(m x m) U Matrix
[[-0.48131357  0.40387904 -0.35577964]
 [ 0.81675553  0.05205373 -0.1307647 ]
 [ 0.00926319 -0.74358446 -0.12029188]
 [ 0.31597641  0.51636621 -0.09545183]
 [ 0.03634224 -0.12091408 -0.91254603]]
 ------------- 
(m x n) Singular Values in Vector Form
[[0.16297867 0.         0.        ]
 [0.         0.06115153 0.        ]
 [0.         0.         0.02556602]]
 ------------- 
(n x n) V^T Matrix
[[ 9.66179546e-01  1.67090046e-01 -1.96412835e-01]
 [ 1.63815921e-01 -9.85941570e-01 -3.29175547e-02]
 [-1.99151775e-01 -3.71281490e-04 -9.79968588e-01]]


In [113]:
#Q4 Compute the solution of $A^TAx=A^Tb$ using Cholesky factorization and QR factorization.

In [114]:
#Let's compute x by Cholesky factorization.

In [115]:
#𝐴𝑇𝐴𝑥=𝐴𝑇𝑏  <=>  𝐿𝐿𝑇𝑥=𝐴𝑇𝑏 
#let's find L first

In [116]:
L= np.linalg.cholesky(np.dot(A.T,A))
print(L)

[[ 1.56843871e+01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 3.95297562e+00  6.03108479e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-9.56365070e-01  2.94814091e+00  1.26646686e+01  0.00000000e+00
   0.00000000e+00]
 [ 6.50328247e+00  1.70660558e+00 -6.61776507e+00  7.84432161e-08
   0.00000000e+00]
 [ 3.07949552e+01  9.99294402e+00  1.51595449e+01  4.57528584e-08
   3.37174788e-07]]


In [118]:
#𝐿𝐿𝑇𝑥=𝐴𝑇𝑏  <=> Ly=𝐴𝑇𝑏 with y =𝐿𝑇𝑥
#now I find y

In [119]:
y= np.linalg.solve(L,np.dot(A.T,b))
print(y)

[[ 1.84897247e+00]
 [ 1.77265903e+00]
 [ 2.72744950e+00]
 [-5.48316920e-08]
 [ 4.95653201e-08]]


In [120]:
#now it is easy to solve x since y= LTx

In [121]:
x =np.linalg.solve(L.T,y)

In [122]:
print(x)

[[ 0.01771853]
 [ 0.45359452]
 [-0.37065713]
 [-0.78473895]
 [ 0.14700186]]


In [123]:
[[-0.025794  ]
 [ 0.16033276]
 [ 0.07383628]
 [-0.0977903 ]
 [ 0.07554213]]
##Let's compute x by QR-factorization.

In [125]:
#Set up new A and new b. that is easier to use QR
A_new = np.dot(A.T,A)
print(A_new)

[[ 246   62  -15  102  483]
 [  62   52   14   36  182]
 [ -15   14  170  -85  192]
 [ 102   36  -85   89  117]
 [ 483  182  192  117 1278]]


In [127]:
b_new = np.dot(A.T,b)
print(b_new)

[[ 29]
 [ 18]
 [ 38]
 [ -3]
 [116]]


In [128]:
Q, R = qr(A_new, 'complete')
print("Matrix Q (m x m)")
print(Q)
print(" ---------- ")
print("Matrix Q^T Q = I (m x m)")
print(Q.T.dot(Q))
print(" ---------- ")
print("Matrix R (m x n)")
print(R)
print(" ---------- ")

Matrix Q (m x m)
[[-0.44306132  0.57008156  0.00799184  0.0055759  -0.69181553]
 [-0.11166586 -0.66463923  0.48237332  0.30652208 -0.46812992]
 [ 0.02701593 -0.42988672 -0.61801402 -0.53464259 -0.38299284]
 [-0.18370835  0.00764685  0.58461866 -0.78034216  0.12441823]
 [-0.86991309 -0.22000147 -0.20864276  0.10600253  0.37427562]]
 ---------- 
Matrix Q^T Q = I (m x m)
[[ 1.00000000e+00 -1.91247376e-16 -2.51844463e-17  1.55400395e-18
   3.01628386e-16]
 [-1.91247376e-16  1.00000000e+00  8.07624200e-17  1.21841162e-16
  -2.17764120e-16]
 [-2.51844463e-17  8.07624200e-17  1.00000000e+00 -2.86798369e-17
   1.31958159e-16]
 [ 1.55400395e-18  1.21841162e-16 -2.86798369e-17  1.00000000e+00
   4.80712453e-17]
 [ 3.01628386e-16 -2.17764120e-16  1.31958159e-16  4.80712453e-17
   1.00000000e+00]]
 ---------- 
Matrix R (m x n)
[[-5.55227881e+02 -1.97835886e+02 -1.41732796e+02 -1.69638455e+02
  -1.36237755e+03]
 [ 0.00000000e+00 -4.49995785e+01 -1.33827180e+02  4.57020754e+01
  -2.08420396e+02]
 [ 

In [130]:
x = np.linalg.solve(R,np.dot(Q.T,b_new))
print(x)

[[-0.025794  ]
 [ 0.16033276]
 [ 0.07383628]
 [-0.0977903 ]
 [ 0.07554213]]


In [143]:
#Q5 Find PCA of A

In [144]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
from scipy.linalg import svd

In [146]:
print("Original (m x n) A Matrix")
print(A)
print(" ------------- ")
m = 3; n= 5
# Column Means
M = mean(A.T, axis = 0)
print("M Vector of Column Means")
print(M)
print(" ------------- ")
#
# Center Columns by subtracting Column Means
C = A.T - M
print("Centered (m x n) Matrix C from A subtract M")
print(C.T)
print(" ------------- ")
#
# Compute Covariance Matrix of the Transpose of Centered Matrix C
V = cov(C.T)
print("Covariance Matrix [cov(C.T)] of the Transpose of Centered Matrix C")
print(V)
print(" ------------- ")
#
Cov_Mat = C.T.dot(C)/(n - 1.)
print("Covariance Matrix of the Transpose of Centered Matrix C")
print(Cov_Mat)
print(" ------------- ")
#
#Perform the SVD of A A^T
U, Sigma, V = svd(V)
print("From SVD --> U Matrix")
print(U)
print(" ------------- ")
print("From SVD --> Singular Values in VECTOR FORM")
print(Sigma)
print(" ------------- ")
print("From SVD --> V^T Matrix")
print(V)
print(" ------------- ")
#
# Eigen_Factorization of Covariance Matrix
Eig_Values, Eig_Vectors = eig(Cov_Mat)
print("EigenValues FROM eig(Cov_Mat)")
print(Eig_Values)
print(" ------------- ")
print("EigenVectors FROM eig(Cov_Mat)")
print(Eig_Vectors)
print(" ------------- ")
#
# Project Data
P = Eig_Vectors.T.dot(C.T)
print("Using Eig_Vectors Projected Original Centered Data in Matrix C")
print(P)
print(" ------------- ")
#
# Project Data
P = U.T.dot(A)
print("Using U Singular Vectors Projected Original Centered Data in Matrix C")
print(P)
print(" ------------- ")

Original (m x n) A Matrix
[[ 1  6 -1  4  7]
 [-7  0 12 -8  2]
 [14  4  5  3 35]]
 ------------- 
M Vector of Column Means
[ 3.4 -0.2 12.2]
 ------------- 
Centered (m x n) Matrix C from A subtract M
[[-2.4  2.6 -4.4  0.6  3.6]
 [-6.8  0.2 12.2 -7.8  2.2]
 [ 1.8 -8.2 -7.2 -9.2 22.8]]
 ------------- 
Covariance Matrix [cov(C.T)] of the Transpose of Centered Matrix C
[[ 11.3   -8.4   20.65]
 [ -8.4   65.2    5.05]
 [ 20.65   5.05 181.7 ]]
 ------------- 
Covariance Matrix of the Transpose of Centered Matrix C
[[ 11.3   -8.4   20.65]
 [ -8.4   65.2    5.05]
 [ 20.65   5.05 181.7 ]]
 ------------- 
From SVD --> U Matrix
[[ 0.11683256 -0.15615305 -0.98079885]
 [ 0.03384562  0.98761442 -0.15320648]
 [ 0.99257475 -0.01529624  0.12067062]]
 ------------- 
From SVD --> Singular Values in VECTOR FORM
[184.30283955  66.44992064   7.44723981]
 ------------- 
From SVD --> V^T Matrix
[[ 0.11683256  0.03384562  0.99257475]
 [-0.15615305  0.98761442 -0.01529624]
 [-0.98079885 -0.15320648  0.12067062]]
