In [ ]:
MATH 3423 HW 2
Student Name: Huy Huynh

In [2]:

#Problem 1
from numpy import array
from scipy.linalg import lu 
import numpy as np
import scipy.linalg as linalg
A = np.array( [[ 7, 1, 6],
            [ 9, 10, -8],
            [ -8, 10, -2],
            [ 9, -7, 9],
            [ 3, 10, 6 ],
            [ -8, 10, 10],
            [ -5, 0, 3]],
            dtype=float ) 
b = np.array( [[ 1],
               [2], 
               [3], 
               [4], 
               [5], 
               [6], 
               [7] ], dtype=float )

A_trans = A.transpose()

B = np.dot(A,A_trans)

print(B)

P, L, U = lu(B) #if B matrix is not identity. then open it under P,L,U
print(P)
print(L)
print(U)

y = np.linalg.solve(L, b)
y
x = np.linalg.solve(U,y)
x




[[  86.   25.  -58.  110.   67.   14.  -17.]
 [  25.  245.   44.  -61.   79.  -52.  -69.]
 [ -58.   44.  168. -160.   64.  144.   34.]
 [ 110.  -61. -160.  211.   11.  -52.  -18.]
 [  67.   79.   64.   11.  145.  136.    3.]
 [  14.  -52.  144.  -52.  136.  264.   70.]
 [ -17.  -69.   34.  -18.    3.   70.   34.]]
[[0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[ 1.          0.          0.          0.          0.          0.
   0.        ]
 [ 0.22727273  1.          0.          0.          0.          0.
   0.        ]
 [ 0.12727273 -0.17088674  1.          0.          0.          0.
   0.        ]
 [-0.52727273  0.04572432  0.44897959  1.          0.          0.
   0.        ]
 [ 0.60909091  0.44870939  0.70408163  0.10180994  1.          0.
   0.        ]
 [ 0.78181818  0.28080773  0.25       -0.48208726 -0.06539852  1.
   0.        ]
 [-0.15454545 -0.30296752  0.

array([[ 8.27379597e+14],
       [ 8.19668273e+13],
       [ 1.15020827e+15],
       [ 3.40304375e+14],
       [ 1.12967325e+14],
       [-1.18966732e+15],
       [ 2.04933447e+15]])

In [3]:
#Problem 2
from numpy import array
from numpy.linalg import cholesky

L = cholesky(B)

LinAlgError: Matrix is not positive definite

In [4]:
Becuase the Matrix is not positive definite,we cannot solve the Cholesky factorization of A* A-transpose. 
However, we can solve the Cholesky factorization of A-transpose * A.

SyntaxError: invalid syntax (<ipython-input-4-204d5f64a84e>, line 1)

In [5]:
#Problem 3
from numpy import array
from numpy.linalg import eig
print("Original (m x m) B Matrix")
print(B)
print(" ------------- ")
# factor
Eig_Values, Eig_Vectors = eig(B)
#
print("EigenValues of B")
print(Eig_Values)
print(" ------------- ")
#
print("EigenVectors of B")
print(Eig_Vectors)
print(" ------------- ")

Original (m x m) B Matrix
[[  86.   25.  -58.  110.   67.   14.  -17.]
 [  25.  245.   44.  -61.   79.  -52.  -69.]
 [ -58.   44.  168. -160.   64.  144.   34.]
 [ 110.  -61. -160.  211.   11.  -52.  -18.]
 [  67.   79.   64.   11.  145.  136.    3.]
 [  14.  -52.  144.  -52.  136.  264.   70.]
 [ -17.  -69.   34.  -18.    3.   70.   34.]]
 ------------- 
EigenValues of B
[ 0.00000000e+00+0.00000000e+00j  5.15285758e+02+0.00000000e+00j
  3.06210772e+02+0.00000000e+00j  3.31503469e+02+0.00000000e+00j
  8.90742995e-15+1.37104212e-14j  8.90742995e-15-1.37104212e-14j
 -1.54977558e-15+0.00000000e+00j]
 ------------- 
EigenVectors of B
[[-0.85683494+0.j          0.12499752+0.j          0.44445567+0.j
   0.22949654+0.j          0.10492431+0.17814131j  0.10492431-0.17814131j
  -0.83908725+0.j        ]
 [ 0.12169311+0.j         -0.12644824+0.j          0.59256921+0.j
  -0.62438468+0.j         -0.12372402+0.12007185j -0.12372402-0.12007185j
   0.20112678+0.j        ]
 [-0.16281956+0.j         -0

In [9]:
#Problem 4
# QR decomposition
from numpy import array
from numpy.linalg import qr
from numpy.linalg import eig
from numpy import array
from scipy.linalg import lu 
import numpy as np
import scipy.linalg as linalg

print(A)
print(" ---------- ")
#
# factor
Q, R = qr(A, 'complete')
print("Matrix Q (m x m)")
print(Q)
print(" ---------- ")
print("Matrix Q^T Q = I (m x m)")
print(Q.T.dot(Q))
print(" ---------- ")
print("Matrix R (m x n)")
print(R)
print(" ---------- ")


[[ 7.  1.  6.]
 [ 9. 10. -8.]
 [-8. 10. -2.]
 [ 9. -7.  9.]
 [ 3. 10.  6.]
 [-8. 10. 10.]
 [-5.  0.  3.]]
 ---------- 
Matrix Q (m x m)
[[-0.36244626 -0.13585128 -0.34060391 -0.74605457 -0.40139537 -0.08700152
   0.09423999]
 [-0.46600234 -0.59722563  0.42795681  0.27305732 -0.23776021  0.22354008
   0.24890953]
 [ 0.4142243  -0.38506363  0.12239091  0.07542182 -0.37896427 -0.69560984
  -0.17885546]
 [-0.46600234  0.22711214 -0.50918172  0.57382623 -0.24373746 -0.28211375
  -0.06101812]
 [-0.15533411 -0.52234492 -0.33425827 -0.03657999  0.72324233 -0.25853798
  -0.00624905]
 [ 0.4142243  -0.38506363 -0.53845627  0.16438467 -0.23699453  0.54182827
  -0.1159417 ]
 [ 0.25889019  0.06240059 -0.15790071  0.0742756  -0.00916984 -0.13630699
   0.93806655]]
 ---------- 
Matrix Q^T Q = I (m x m)
[[ 1.00000000e+00 -5.08079358e-19  5.09571533e-17 -7.13632916e-17
  -2.80273541e-18 -2.94894183e-17 -3.13319262e-18]
 [-5.08079358e-19  1.00000000e+00  7.91016347e-17  1.66437948e-16
   5.13036139e-17  

In [12]:
#this is the case that i cannot solve Rx=Q_tranposexb
#then i apply the least square approach to solve it.
R_new = np.delete(R,[3,4,5,6],0)

R_new
#np.linalg.solve(R_new,Q.T @ b)



array([[-19.31320792,   4.97069158,   0.51778037],
       [  0.        , -20.62261441,  -0.02067019],
       [  0.        ,   0.        , -18.15850975]])

In [10]:
z = np.dot(A_trans, b) 

R_trans = R.transpose()

y = np.dot(R_trans,R)

x = linalg.solve(y, z)

print("x is")
print(x)


x is
[[0.00302067]
 [0.29357068]
 [0.39439241]]


In [7]:
#Problem 5
# Singular Value Decomposition
from numpy import array
from numpy.linalg import eig
from scipy.linalg import svd
# define a matrix
U, Sigma, V = np.linalg.svd(A, full_matrices=False)
c = np.dot(U.T,b)
w = np.linalg.solve(np.diag(Sigma),c)
x = np.dot(V.T,w)
print("x is")
print(x)

x is
[[0.00302067]
 [0.29357068]
 [0.39439241]]
